server:
  port: 8080

spring:
  application:
    name: KotlinMultiSample
  datasource:
    url:  jdbc:postgresql://db.oytsatbsgirfatefekdj.supabase.co:5432/postgres
    username: postgres
    password: wjdgkdms!@#
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false # 권장: OSIV 비활성화 (경고 해결)
    database: postgresql
    hibernate:
      ddl-auto: update # create, update, validate, none
    show-sql: true # SQL 출력
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        use_sql_comments: true  # SQL 주석 표시
        # dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics
